### PR TITLE
Removed gt50 nonsense, converted to svgs

### PR DESCRIPTION
**Pull request by miller-kevin**
Found a bug when jumping too low below 50% that I hadn't caught with the 10% jumps. Decided the better solution was to remove the gt50 calculations and just use an svg

### CODE REVIEW

**Comment by miller-kevin** [comment]
@teobais this is ready for review, when you get a chance

**Comment by teobais** [comment]
Thank you @miller-kevin , will do my best to have a look at it in the weekend.

**Review by teobais — COMMENTED** [review]
@miller-kevin thanks for this. Is there a specific reason I also see the on-hover animation having a different effect? The default one was something like a ripple effect / expand the 
inner circle and text on hover and make circle line thinner, whereas the newly introduced code does the latter plus a slight shrinking on the circle line which doesn't feel right as a default behavior. That being said, I would prefer to keep it as an configuration option so that the user can choose between 1) the default on hover effect (no additional config needed) as done [here](https://teobais.github.io/percircle/), and 2) the newly introduced. Regarding the on hover effects' naming, I would go for "vivid" for the already existing one (1) , and "smooth" for the one introduced here (2), unless you have a better suggestion.

**Comment by miller-kevin** [comment]
@teobais that was primarily a result of css not being able to work with the r property on an svg. I'll see if I can find a work around to get the old animation working

**Comment by miller-kevin** [comment]
@teobais apparently the issue I was having is just a vs code bug https://github.com/microsoft/vscode/issues/85828

I'll try to fix it on Monday, but I think any maintainer will need to add this setting to ignore the warning until it's fixed in vs code

**Comment by miller-kevin** [comment]
@teobais The bug you reported is fixed, take a look when you get a chance, please

**Comment by teobais** [comment]
@miller-kevin indeed, it seems to be fixed, thanks. However, the second part of my last comment seems to still be the case. Our transitions should be identical to what we have at percircle. That is, on hover we should have an inside out transition rather an "outside-in" as this PR / current state of percircle-vue suggests. Could we also fix that? Then, I see two options: default should be the inside out transition (named as "vivid") and an additional option if the user wants an outside in animation (current state of this PR) named as "smooth"

**Comment by miller-kevin** [comment]
@teobais I don't understand what you mean, you want the bugged animation to remain in there but as a configurable option? It definitely wasn't intended. The animation here matches the original percircle animation, as shown in the following gif
Percircleanimation

**Comment by miller-kevin** [comment]
@teobais I see the left side grows a little bit, so I've lowered the hover radius change so that it doesn't. I don't see an outside-in effect in that gif, so I'll need some more information from you to fix it

**Comment by teobais** [comment]
@miller-kevin what is your dev environment? I'm on a Mac and have tried all browsers yet the animation doesn't seem to be as nice as your left-hand side of your gif above

Two examples from my end
- http://g.recordit.co/QKMn5SSIvb.gif
- http://g.recordit.co/q3XIsxO0ve.gif

**Comment by miller-kevin** [comment]
@teobais I'm on windows using chrome. The animation you're seeing is the animation that used to be there, Have you gotten latest and cleared cache?

**Comment by teobais** [comment]
@miller-kevin yes. I think I'm breaking my head here, reason being the recently introduced font-size reduction of the circle's inner text, which doesn't seem to be the case in your screenshot.

**Review by teobais — APPROVED** [review]

**Comment by teobais** [comment]
LGTM. Thanks @miller-kevin 🎉

**Comment by miller-kevin** [comment]
@teobais Using the demo page:
Percircleanimation

Is it still giving you trouble?

**Pull request merged**
